[package]
name = "lottery-dct"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false

[lib]
path = "src/lottery.rs"

[dependencies.dharitri-sc]
version = "=0.13.4"

[dev-dependencies.dharitri-sc-scenario]
version = "=0.13.4"
